<?xml version="1.0" encoding="UTF-8"?>
<!--
  ~ Copyright (c) 2026, WSO2 LLC. (http://www.wso2.com).
  ~
  ~ WSO2 LLC. licenses this file to you under the Apache License,
  ~ Version 2.0 (the "License"); you may not use this file except
  ~ in compliance with the License.
  ~ You may obtain a copy of the License at
  ~
  ~ http://www.apache.org/licenses/LICENSE-2.0
  ~
  ~ Unless required by applicable law or agreed to in writing,
  ~ software distributed under the License is distributed on an
  ~ "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
  ~ KIND, either express or implied.  See the License for the
  ~ specific language governing permissions and limitations
  ~ under the License.
  -->
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.wso2</groupId>
        <artifactId>wso2</artifactId>
        <version>1.4</version>
    </parent>

    <scm>
        <url>https://github.com/wso2-extensions/identity-serializer-fory.git</url>
        <developerConnection>scm:git:https://github.com/wso2-extensions/identity-serializer-fory.git</developerConnection>
        <connection>scm:git:https://github.com/wso2-extensions/identity-serializer-fory.git</connection>
        <tag>HEAD</tag>
    </scm>

    <groupId>org.wso2.carbon.extension.identity.serializer.fory</groupId>
    <artifactId>identity-serializer-fory</artifactId>
    <version>1.0.0-SNAPSHOT</version>
    <modules>
        <module>org.wso2.carbon.identity.serializer.fory</module>
    </modules>

    <packaging>pom</packaging>
    <name>Apache Fory based session serializer</name>

    <build>
        <pluginManagement>
            <plugins>
                <plugin>
                    <groupId>org.apache.felix</groupId>
                    <artifactId>maven-bundle-plugin</artifactId>
                    <version>${maven.bundle.plugin.version}</version>
                    <extensions>true</extensions>
                    <configuration>
                        <obrRepository>NONE</obrRepository>
                        <instructions />
                    </configuration>
                </plugin>
            </plugins>
        </pluginManagement>
    </build>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.apache.fory</groupId>
                <artifactId>fory-core</artifactId>
                <version>${org.apache.fory.version}</version>
                <scope>provided</scope>
            </dependency>
            <dependency>
                <groupId>org.wso2.carbon.identity.framework</groupId>
                <artifactId>org.wso2.carbon.identity.application.authentication.framework</artifactId>
                <version>${carbon.identity.framework.version}</version>
                <scope>provided</scope>
            </dependency>
            <dependency>
                <groupId>org.wso2.carbon.identity.framework</groupId>
                <artifactId>org.wso2.carbon.identity.core</artifactId>
                <version>${carbon.identity.framework.version}</version>
                <scope>provided</scope>
            </dependency>
            <dependency>
                <groupId>org.wso2.carbon.identity.inbound.auth.oauth2</groupId>
                <artifactId>org.wso2.carbon.identity.oauth</artifactId>
                <version>${carbon.identity.oauth.version}</version>
                <scope>provided</scope>
            </dependency>
            <dependency>
                <groupId>org.wso2.carbon.identity.inbound.auth.oauth2</groupId>
                <artifactId>org.wso2.carbon.identity.oidc.session</artifactId>
                <version>${carbon.identity.oauth.version}</version>
                <scope>provided</scope>
            </dependency>
            <dependency>
                <groupId>org.wso2.carbon.identity.inbound.auth.oauth2</groupId>
                <artifactId>org.wso2.carbon.identity.oauth.rar</artifactId>
                <version>${carbon.identity.oauth.version}</version>
                <scope>provided</scope>
            </dependency>
            <dependency>
                <groupId>org.testng</groupId>
                <artifactId>testng</artifactId>
                <version>${testng.version}</version>
                <scope>test</scope>
            </dependency>
            <dependency>
                <groupId>org.mockito</groupId>
                <artifactId>mockito-all</artifactId>
                <version>${org.mockito.version}</version>
                <scope>test</scope>
            </dependency>
            <dependency>
                <groupId>org.jacoco</groupId>
                <artifactId>org.jacoco.agent</artifactId>
                <classifier>runtime</classifier>
                <version>${jacoco.version}</version>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <properties>
        <org.apache.fory.version>1.6.0</org.apache.fory.version>
        <carbon.identity.framework.package.import.version.range>[7.8.0,8.0.0)</carbon.identity.framework.package.import.version.range>
        <carbon.identity.oauth.package.import.version.range>[7.0.0,8.0.0)</carbon.identity.oauth.package.import.version.range>
        <org.mockito.version>1.10.19</org.mockito.version>
        <maven.surefire.plugin.version>2.22.0</maven.surefire.plugin.version>
        <jacoco.version>0.8.14</jacoco.version>
        <commons-logging.osgi.version.range>[1.2,2)</commons-logging.osgi.version.range>
        <carbon.identity.framework.version>7.8.586</carbon.identity.framework.version>
        <carbon.identity.oauth.version>7.0.385</carbon.identity.oauth.version>
        <osgi.framework.imp.pkg.version.range>[1.7.0, 2.0.0)</osgi.framework.imp.pkg.version.range>
        <osgi.service.component.imp.pkg.version.range>[1.2.0, 2.0.0)</osgi.service.component.imp.pkg.version.range>
        <maven.bundle.plugin.version>5.1.9</maven.bundle.plugin.version>
        <testng.version>6.9.10</testng.version>
    </properties>
</project>
